# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.152.1+26.2

# https://modrinth.com/mod/fabric-language-kotlin/versions
fabric_kotlin_version=1.13.12+kotlin.2.4.0

# Mod Properties
mod_version=0.5.4
maven_group=xyz.thewhitedog9487

# Dependencies

# https://modrinth.com/mod/modmenu/versions
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=20.0.0-beta.2